export const exerciseLibrary = [
  // BEGINNER - HOME FRIENDLY
  {
    name: "Push-Ups",
    type: "bodyweight",
    goals: ["muscleGain", "fatLoss", "endurance"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "beginner",
    muscleGroups: ["chest", "triceps", "core"],
  },
  {
    name: "Bodyweight Squats",
    type: "bodyweight",
    goals: ["fatLoss", "muscleGain"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "beginner",
    muscleGroups: ["legs", "glutes"],
  },
  {
    name: "Wall Sits",
    type: "isometric",
    goals: ["endurance", "fatLoss"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "beginner",
    muscleGroups: ["quads", "glutes"],
  },
  {
    name: "Plank",
    type: "core",
    goals: ["fatLoss", "endurance"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "beginner",
    muscleGroups: ["core"],
    duration: "60 sec",
  },
  {
    name: "Mountain Climbers",
    type: "cardio",
    goals: ["fatLoss", "endurance"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "beginner",
    muscleGroups: ["core", "legs"],
  },
  {
    name: "Glute Bridges",
    type: "bodyweight",
    goals: ["muscleGain", "rehab"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "beginner",
    muscleGroups: ["glutes", "hamstrings"],
  },
  {
    name: "Bird Dog",
    type: "core/stability",
    goals: ["rehab", "endurance"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "beginner",
    muscleGroups: ["core", "lower back"],
  },

  // INTERMEDIATE
  {
    name: "Pull-Ups",
    type: "compound",
    goals: ["strength", "muscleGain"],
    equipment: "pull-up bar",
    environment: ["gym", "home"],
    level: "intermediate",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Dumbbell Shoulder Press",
    type: "compound",
    goals: ["muscleGain", "strength"],
    equipment: "dumbbells",
    environment: ["gym", "home"],
    level: "intermediate",
    muscleGroups: ["shoulders", "triceps"],
  },
  {
    name: "Bent Over Rows",
    type: "compound",
    goals: ["muscleGain", "strength"],
    equipment: "barbell or dumbbells",
    environment: ["gym", "home"],
    level: "intermediate",
    muscleGroups: ["back", "biceps"],
  },
  {
    name: "Bulgarian Split Squats",
    type: "bodyweight/weighted",
    goals: ["muscleGain", "balance"],
    equipment: "dumbbells (optional)",
    environment: ["gym", "home"],
    level: "intermediate",
    muscleGroups: ["quads", "glutes"],
  },
  {
    name: "Rowing Machine",
    type: "cardio",
    goals: ["endurance", "fatLoss"],
    equipment: "rowing machine",
    environment: ["gym"],
    level: "all",
    muscleGroups: ["full body"],
    duration: "15 min",
  },
  {
    name: "Battle Ropes",
    type: "cardio/conditioning",
    goals: ["fatLoss", "endurance"],
    equipment: "battle ropes",
    environment: ["gym"],
    level: "intermediate",
    muscleGroups: ["arms", "shoulders", "core"],
  },

  // ADVANCED
  {
    name: "Deadlifts",
    type: "compound",
    goals: ["strength", "muscleGain"],
    equipment: "barbell",
    environment: ["gym"],
    level: "intermediate",
    muscleGroups: ["back", "legs", "glutes"],
  },
  {
    name: "Barbell Squats",
    type: "compound",
    goals: ["strength", "muscleGain"],
    equipment: "barbell",
    environment: ["gym"],
    level: "intermediate",
    muscleGroups: ["legs", "glutes", "core"],
  },
  {
    name: "Overhead Barbell Press",
    type: "compound",
    goals: ["strength", "muscleGain"],
    equipment: "barbell",
    environment: ["gym"],
    level: "intermediate",
    muscleGroups: ["shoulders", "triceps"],
  },
  {
    name: "Snatch",
    type: "olympic",
    goals: ["strength", "power"],
    equipment: "barbell",
    environment: ["gym"],
    level: "advanced",
    muscleGroups: ["full body"],
  },

  // CARDIO / ENDURANCE
  {
    name: "Running",
    type: "cardio",
    goals: ["endurance", "fatLoss"],
    equipment: "none",
    environment: ["home", "gym", "outdoor"],
    level: "all",
    muscleGroups: ["legs", "cardio"],
    duration: "20–30 min",
  },
  {
    name: "Cycling",
    type: "cardio",
    goals: ["endurance", "fatLoss"],
    equipment: "bike",
    environment: ["gym", "outdoor"],
    level: "all",
    muscleGroups: ["legs", "cardio"],
    duration: "30 min",
  },
  {
    name: "Jump Rope",
    type: "cardio",
    goals: ["endurance", "fatLoss", "coordination"],
    equipment: "jump rope",
    environment: ["home", "gym"],
    level: "beginner",
    muscleGroups: ["full body"],
    duration: "10 min",
  },

  // CORE / REHAB
  {
    name: "Side Plank",
    type: "core",
    goals: ["endurance", "core stability"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "all",
    muscleGroups: ["obliques", "core"],
    duration: "30–60 sec",
  },
  {
    name: "Hollow Body Hold",
    type: "core/isometric",
    goals: ["core strength", "gymnastics"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "intermediate",
    muscleGroups: ["core"],
    duration: "30 sec",
  },

  // FLEXIBILITY & MOBILITY
  {
    name: "Dynamic Lunges with Twist",
    type: "mobility",
    goals: ["mobility", "injuryPrevention"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "all",
    muscleGroups: ["hips", "core", "spine"],
  },
  {
    name: "Cat-Cow Stretch",
    type: "mobility",
    goals: ["mobility", "rehab"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "all",
    muscleGroups: ["spine", "back"],
  },
  {
    name: "World's Greatest Stretch",
    type: "mobility/dynamic warmup",
    goals: ["mobility", "performance"],
    equipment: "none",
    environment: ["home", "gym"],
    level: "all",
    muscleGroups: ["hips", "hamstrings", "spine"],
  },
];
